# 確認用docker-compose.yml
version: "3.8"
services: 
  metabase:
    build:
      context: .
      dockerfile: ./docker/metabase/DockerFile
    volumes: 
      - ./docker/metabase:/metabase.db
  
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/DockerFile
    volumes:
      - ./docker/nginx/ssl:/etc/pki/tls/certs 
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 16001:443
      - 16002:80

  db:
    build: 
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - 16003:3306

volumes:
  db-store: